### PR TITLE
Fixes MYRIAD-43, MYRIAD-98

### PR DESCRIPTION
**Pull request by klucar**
com.ebay namespace changed to org.apache
2 space indentation requirement now in checkstyles
all files updated to match 2-space indentation.

### CODE REVIEW

**Comment by smarella** [comment]
@klucar: This patch is not applying cleanly anymore as I merged a couple of other PRs into the master branch. Can you please rebase?

Also, the cause for the failure wasn't apparent when I tried it last week. I'll try it out again today.

**Comment by klucar** [comment]
Santosh,

I'll do it one more time, but no matter what its going to be painful unless
you merge nothing else before it. Anything after will have to be
refactored. If there's some outstanding pulls you want first I'll wait.
Just let me know when.

**Comment by smarella** [comment]
Jim.. Agreed! Please go ahead and rebase. I'll have this one merged in before anything else.

Have you figure out the issue causing the build failure? I looked at the checkstyle.xml to see the policy for indentation, but apparently nothing stood out.

**Comment by klucar** [comment]
Ok, I've been away so I haven't looked at the build failure. I'm sure it
will all be different once I redo it.

**Comment by klucar** [comment]
I worked on this a bit this morning. I found the problem the build had, but
I think it showed that one of my reformatting scripts was over zealous.
I'll work it out.

-Jim

**Comment by klucar** [comment]
Submitted a new PR that passed CI.
https://github.com/apache/incubator-myriad/pull/22

**Pull request closed without merging**
