### PR TITLE
MYRIAD-180 Build should not pollute sources

### PR DESCRIPTION
**Pull request by ZJaffee**
Not sure if this follows best practices, but node_modules is now built outside of the src dir.

### CODE REVIEW

**Comment by DarinJ** [comment]
@ZJaffee looks like something broke in the build here.

**Comment by ZJaffee** [comment]
This is weird, it worked locally and the build server is saying that it cannot find nodejs, I'll dive into this later tonight.

**Comment by DarinJ** [comment]
@ZJaffee I screw up here, and made a typo when I merged #57, feel free to resubmit this PR if you want to continue working on it.

**Comment by oscarfmdc** [comment]
Merged in https://github.com/apache/incubator-myriad/pull/131

**Pull request closed without merging**
