### PR TITLE
Create DISCLAIMER

### PR DESCRIPTION
**Pull request by smarella**
Incubator projects are required to have a DISCLAIMER file as described here: http://incubator.apache.org/guides/branding.html#disclaimers

### CODE REVIEW

**Comment by klucar** [comment]
This is now in the footer of each page.

Disclaimer:Apache Mesos is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by the Apache Incubator. Incubation is required of all newly accepted projects until a further review indicates that the infrastructure, communications, and decision making process have stabilized in a manner consistent with other successful ASF projects. While incubation status is not necessarily a reflection of the completeness or stability of the code, it does indicate that the project has yet to be fully endorsed by the ASF.

**Comment by klucar** [comment]
Preview here

http://klucar.github.io/myriad-site/

**Comment by smarella** [comment]
Apache Mesos -> Apache Myriad

----------------------

**Comment by klucar** [comment]
Doh! Fixed.

**Comment by adam-mesos** [comment]
LGTM. How about the LICENSE and NOTICE files?

**Comment by smarella** [comment]
We have LICENSE and NOTICE file already in the project.

**Comment by adam-mesos** [comment]
Right on. Ship it! :rocket:

**Pull request closed without merging**
